export const SOURCE_HEADERS = [
  'TIMESTAMP', 'REQUEST ID', 'DATE REQUESTED', 'INQUIRY ORIGIN', 'COMPANY NAME (Please complete company name)',
  'DEADLINE MM/DD/YYYY', 'DATE QUOTED MM/DD/YYYY', 'REQUESTOR EMAIL', 'ACCOUNT', 'RFQ/REQUEST',
  'SALES REFERENCE', 'QUOTE NO. (QU-000000)', 'PROCUREMENT- REASON OF QUOTE DELAYS', 'CUSTOMER FEEDBACK/ CS COMMENTS',
  'ASSIGNED SALES', 'CONTACT PERSON', 'CONTACT NUMBER', 'EMAIL ADDRESS', 'PROCUREMENT ASSIGNEE', 'PRODUCT INQUIRY',
  'COSTING SHEET', 'PRODUCT CATEGORY', 'QUANTITY', 'COST PER UNIT', 'SUPPLIER PRICE', 'QUOTED PRICE TO CLIENT',
  'TOTAL PRICE OF ITEMS WITH QUANTITY', 'STATUS', 'QDW NO. (PLEASE ADD ONCE QUOTE IS WON)', 'REASONS- QUOTE NOT PUSHING THROUGH',
  'QUOTE REVISION', 'CUSTOMER PO NUMBER', 'CUSTOMER PO LINK', 'SUPPLIER', 'SUPPLIER EMAIL', 'SUPPLIER CONTACT PERSON',
  'SUPPLIER CONTACT NUMBER', 'SUPPLIER NOTES', 'SUPPLIER QUOTE', 'PAYMENT TERMS', 'PO Status ( Procurement & Acctng)',
  'PO DATE', 'WAREHOUSE', 'DELIVERY ADDRESS', 'DELIVERY CONTACT PERSON', 'DELIVERY CONTACT NUMBER', 'DELIVERY EMAIL',
  'ETA', 'LOGISTICS PARTNER', 'PROOF OF DELIVERY', 'INVOICE NUMBER', 'FULFILMENT COMMENTS', 'LAST UPDATE',
  'INTERNAL REFERENCE', 'SOURCE LINK', 'CLOSED DATE', 'CLIENT ACCOUNT OWNER', 'CUSTOMER TYPE', 'Item Status ( Delivered)',
  'BUDGET', 'CURRENCY', 'DELIVERY NOTES', 'CLIENT-FACING STATUS', 'PRIORITY', 'ESTIMATED RFQ VALUE',
];

export const FIELD_MAP = {
  requestedDate: ['DATE REQUESTED'],
  inquiryOrigin: ['INQUIRY ORIGIN'],
  clientName: ['COMPANY NAME (Please complete company name)'],
  deadline: ['DEADLINE MM/DD/YYYY'],
  dateQuoted: ['DATE QUOTED MM/DD/YYYY'],
  quoteNumber: ['QUOTE NO. (QU-000000)'],
  procurementDelayReason: ['PROCUREMENT- REASON OF QUOTE DELAYS'],
  customerComments: ['CUSTOMER FEEDBACK/ CS COMMENTS'],
  assignedSales: ['ASSIGNED SALES'],
  clientContactName: ['CONTACT PERSON'],
  clientContactNumber: ['CONTACT NUMBER'],
  clientEmail: ['EMAIL ADDRESS'],
  procurementAssignee: ['PROCUREMENT ASSIGNEE'],
  productInquiry: ['PRODUCT INQUIRY', 'RFQ/REQUEST'],
  costingSheet: ['COSTING SHEET'],
  productCategory: ['PRODUCT CATEGORY'],
  quantity: ['QUANTITY'],
  quotedUnitPrice: ['QUOTED PRICE TO CLIENT'],
  totalQuotedAmount: ['TOTAL PRICE OF ITEMS WITH QUANTITY'],
  operationalStatus: ['STATUS'],
  qdwNumber: ['QDW NO. (PLEASE ADD ONCE QUOTE IS WON)'],
  nonProceedingReason: ['REASONS- QUOTE NOT PUSHING THROUGH'],
  customerPoNumber: ['CUSTOMER PO NUMBER'],
  customerPoLink: ['CUSTOMER PO LINK'],
  supplierName: ['SUPPLIER'],
  supplierEmail: ['SUPPLIER EMAIL'],
  supplierContactName: ['SUPPLIER CONTACT PERSON', 'SUPPLIER CONTACT NAME'],
  supplierContactNumber: ['SUPPLIER CONTACT NUMBER'],
  poStatus: ['PO Status ( Procurement & Acctng)'],
  deliveryAddress: ['DELIVERY ADDRESS'],
  deliveryContactName: ['DELIVERY CONTACT PERSON'],
  deliveryContactNumber: ['DELIVERY CONTACT NUMBER'],
  deliveryEmail: ['DELIVERY EMAIL'],
  eta: ['ETA'],
  proofOfDelivery: ['PROOF OF DELIVERY'],
  invoiceNumber: ['INVOICE NUMBER'],
  fulfilmentComments: ['FULFILMENT COMMENTS'],
  itemDeliveryStatus: ['Item Status ( Delivered)'],
  clientFacingStatus: ['CLIENT-FACING STATUS'],
  priority: ['PRIORITY'],
  estimatedRfqValue: ['ESTIMATED RFQ VALUE'],
  deliveryNotes: ['DELIVERY NOTES'],
};

export function valueFor(sourceRecord, fieldName) {
  const candidates = FIELD_MAP[fieldName] || [];
  const header = candidates.find((candidate) => Object.prototype.hasOwnProperty.call(sourceRecord, candidate));
  return header ? String(sourceRecord[header] ?? '').trim() : '';
}
